### ISSUE TITLE
Max spec len error

### ISSUE THREAD

**Issue by MohanThippeswamy** [quickvc/QuickVoice-Conversion#19]
Hi quickVc, 
I'm getting dimension error for my own dataset. what should I check for. 
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

Traceback (most recent call last):
  File "data_utils_new_new.py", line 312, in <module>
    for batch_idx, (c, spec, y) in enumerate(train_loader):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 644, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "data_utils_new_new.py", line 124, in __call__
    max_spec_len = max([x[1].size(1) for x in batch])
  File "data_utils_new_new.py", line 124, in <listcomp>
    max_spec_len = max([x[1].size(1) for x in batch])
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by zxj329** [comment]
have u solved this problem?
